django_snippets/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from django_snippets.settings import DEBUG

urlpatterns = [
    path('', include('snippets.urls')),
    path('admin/', admin.site.urls),
]

if not DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

snippets/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from snippets.views.snippets import *
from snippets.views.user import *
from snippets.views.language import *

app_name = "snippets"

urlpatterns = [
    path('', SnippetListView.as_view(), name='index'),
    path('login/', LoginAppView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='snippets:login'), name='logout'),
    path('snippets/<int:pk>/', LanguageListView.as_view(), name='language'),
    path('snippets/user/<int:pk>/', UserSnippetsView.as_view(), name='user_snippets'),
    path('snippets/snippet/<int:pk>/', SnippetDetailView.as_view(), name='snippet'),
    path('snippets/add/<int:pk>/', SnippetCreateView.as_view(), name='snippet_add'),
    path('snippets/edit/<int:pk>/', SnippetUpdateView.as_view(), name='snippet_edit'),
    path('snippets/delete/<int:pk>/', SnippetDeleteView.as_view(), name='snippet_delete'),
]

snippets/models/language.py
from django.db import models

class Language(models.Model):
    name = models.CharField(verbose_name="Name", max_length=50)
    slug = models.CharField(verbose_name="Slug", max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Language"
        verbose_name_plural = "Laguages"

snippets/models/snippet.py
from django.db import models
from django.contrib.auth.models import User

from snippets.models.language import Language

class Snippet(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    language = models. ForeignKey(Language, on_delete=models.PROTECT)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    snippet = models.TextField()
    public = models.BooleanField(default=False)

snippets/forms/snippets.py
from django.forms import ModelForm, Form

from snippets.models.snippet import Snippet

class SnippetForm(ModelForm):
    class Meta:
        model = Snippet
        fields = [
            'name',
            'language',
            'description',
            'snippet',
            'public'
        ]

snippets/views/language.py
from django.views.generic import CreateView, ListView, UpdateView, DeleteView

from snippets.models.language import Language
from snippets.models.snippet import Snippet

class LanguageCreateView(CreateView):
    model = Language
    template_name = ""

class LanguageListView(ListView):
    model = Snippet
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Language Snippets"
        context['object_list'] = Snippet.objects.filter(language_id=self.kwargs['pk'])
        return context

class LanguageUpdateView(UpdateView):
    model = Language
    template_name = ""

class LanguageDeleteView(DeleteView):
    model = Language
    template_name = ""

snippets/views/snippets.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import render

from pygments import highlight
import pygments.lexers as lx
from pygments.formatters import HtmlFormatter

from snippets.models.snippet import Snippet
from snippets.forms.snippets import SnippetForm


class SnippetCreateView(CreateView):
    model = Snippet
    form_class = SnippetForm
    template_name = "snippets/snippet_add.html"
    success_url = reverse_lazy('snippets:index')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        form = self.form_class(request.POST)
        if form.is_valid():
            snippet = form.save(commit=False)
            snippet.user = self.request.user
            snippet.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            self.object = None
            context = self.get_context_data(**kwargs)
            return render(request, self.template_name, context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Add Snippet"
        return context

class SnippetListView(ListView):
    model = Snippet
    template_name = "index.html"

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Snippets"
        context['object_list'] = Snippet.objects.filter(public=True)
        return context

class SnippetUpdateView(UpdateView):
    model = Snippet
    template_name = "snippets\snippet_edit.html"
    form_class = SnippetForm
    success_url = reverse_lazy('snippets:index')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Edit Snippet"
        return context

class SnippetDeleteView(DeleteView):
    model = Snippet
    template_name = "snippets/snippet_delete.html"
    success_url = reverse_lazy('snippets:index')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Delete Snippet"
        return context

class SnippetDetailView(TemplateView):
    template_name = "snippets/snippet.html"

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Snippet Detail"
        context['snippet'] = Snippet.objects.get(pk=self.kwargs['pk'])
        snip_lang = Snippet.objects.get(pk=self.kwargs['pk']).language.slug
        lexer = lx.get_lexer_by_name(snip_lang)
        context['code'] = highlight(Snippet.objects.get(pk=self.kwargs['pk']).snippet, lexer, HtmlFormatter(), outfile=None)
        return context

snippets/views/user.py
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView
from django.shortcuts import redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from snippets.models.snippet import Snippet

class LoginAppView(LoginView):
    template_name = "login.html"
    
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('snippets:index')
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class UserSnippetsView(TemplateView):
    template_name = "snippets/user_snippets.html"

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = User.objects.get(pk=self.kwargs['pk'])
        context['public_snippets'] = Snippet.objects.filter(user_id=self.kwargs['pk']).filter(public=True)
        if self.request.user.id == User.objects.get(pk=self.kwargs['pk']).id:
            context['private_snippets'] = Snippet.objects.filter(user_id=self.kwargs['pk']).filter(public=False)
        return context

snippets/templates/base.html
<!doctype html>
<html lang="en">
    {% load static %}
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        {% load i18n %}
        {% load pygmentize %}
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <style>{% pygments_css %}</style>  <!-- load css for pygments -->
        <title>Django Snippets</title>
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <a class="navbar-brand" href="{% url 'snippets:index' %}">Snippets Project</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Snipets</a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'snippets:snippet_add' request.user.id %}">Cargar Snippets</a>
                                <a class="dropdown-item" href="{% url 'snippets:index' %}">Listado de Snippets</a>                
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'snippets:logout' %}" tabindex="-1">Salir</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <div class="container">
          {% block content %}
          {% endblock %}
        </div>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

snippets/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="row justify-content-md-center" style="padding-top:20px;">
    <div class="col-md-8">
        <h1>Snippets</h1>
        <br>
        {% for obj in object_list %}
        <!-- SNIPPET -->
        <div class="card">
            <h5 class="card-header">{{obj.name}} <a href="{% url 'snippets:user_snippets' obj.user.id %}"  class="float-right"><small>{{obj.user.username}}</small></a></h5>
            <div class="card-body">
                <a href="{% url 'snippets:language' obj.language.id %}"><h5 class="card-title">{{obj.language.name}}</h5></a> 
                <h6 class="card-subtitle mb-2 text-muted">Creado: {{obj.created}}</h6>
                <p class="card-text">{{obj.description}}</p>
                <hr>
                <a href="{% url 'snippets:snippet' obj.id %}" class="btn btn-primary">Ver</a>
                {% if request.user.id == obj.user.id %}
                <a href="{% url 'snippets:snippet_edit' obj.id %}" class="btn btn-info">Editar</a>
                <a href="{% url 'snippets:snippet_delete' obj.id %}" class="btn btn-danger">Eliminar</a> 
                {% endif %}
            </div>
        </div>
        <br>
        <!-- FIN SNIPPET -->
        {% endfor %}
  </div>
</div>
{% endblock %}

snippets/templates/login.html
<!doctype html>
<html lang="en">
  {% load static %}
  {% load widget_tweaks %}
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'snippets\css\signin.css' %}">
        <title>Django Snippets</title>
    </head>
    <body>
        <!-- FORMULARIO -->
        <form class="form-siging" action="." method="post">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ next }}">
            <img class="mb-4" src="{% static 'lib\bootstrap-5.0.2\site\static\docs\5.0\assets\img\favicons\safari-pinned-tab.svg' %}" alt="" width="72" height="72">
            <h1 class="h3 mb-3 font-weight-normal">Ingresar</h1>
            <label for="inputEmail" class="sr-only">{{form.username.label}} </label>
            {{form.username|add_class:'form-control'|attr:'placeholder:username'|attr:'autofocus'}}
            <label for="inputPassword" class="sr-only">{{form.password.label}}</label>
            {{form.password|add_class:'form-control'|attr:'placeholder:Password'}}
            <button class="btn btn-lg btn-primary btn-block" type="submit">Entrar</button>
        </form>
        <!-- FIN FORMULARIO -->
  
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script src="{% static 'lib\sweetalert2-9.10.0\sweetalert2.all.min.js' %}"></script>
        <script type="application/javascript">
			{% if form.errors %}
				var errors = '';
				{% for field in form %}
					{% for error in field.errors %}
						errors += '{{ error }}\n';
					{% endfor %}
				{% endfor %}
				{% for error in form.non_field_errors %}
					errors += '{{ error }}\n';
				{% endfor %}
				Swal.fire({
					title: 'Error',
					text: errors,
					icon: 'error'
				});
			{% endif %}
		</script>
    </body>
</html>

snippets/templates/snippets/snippet.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load pygmentize %}
{% block content %}
<div class="row justify-content-md-center">
  <div class="col-md-8">
    <br>
    <div class="card">
      <h5 class="card-header">{{snippet.name}} <a href="{% url 'snippets:user_snippets' snippet.user.id%}"  class="float-right"><small>{{snippet.user.username}}</small></a></h5>
      <div class="card-body">
        <a href="{% url 'snippets:language' snippet.language.id %}"><h5 class="card-title">{{snippet.language.name}}</h5></a> 
        <h6 class="card-subtitle mb-2 text-muted">Creado: {{snippet.created}}</h6>
        <p class="card-text">{{snippet.description}}</p>
        <div style="background-color:lightgray;border-radius: 5px;">
          <!-- Código del Snippet -->
          <div class="container">
            <div class="sourcecode">
                {{ code|pygmentize:"python3" }}  <!-- highlighting -->
            </div>
          </div>
          <!-- Código del Snippet -->
        </div>
        <hr>
        <br>
        {% if request.user.id == snippet.user.id %}
        <a href="{% url 'snippets:snippet_edit' snippet.id %}" class="btn btn-info">Editar</a>
        <a href="{% url 'snippets:snippet_delete' snippet.id %}" class="btn btn-danger">Eliminar</a>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

snippets/templates/snippets/snippet_add.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row justify-content-md-center">
  <div class="col-md-6">
    <br>
    <form action="." method="post">
      {% csrf_token %}
      {{form|crispy}}
      <button type="submit" class="btn btn-primary">Crear</button>
    </form>
  </div>
</div>

{% endblock %}

snippets/templates/snippets/snippet_delete.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="row justify-content-md-center">
    <div class="col-md-8">
        <h1>Eliminar Snippet : {{snippet.name}}</h1>
        <div class="card">
            <div class="card-body">
                <form action="." method="post">
                    {% csrf_token %}
                    <p class="card-text">¿Está seguro de querer eliminar el snippet?</p>
                    <div class="form-group">
                        <button class="btn-danger" type="submit">Eliminar</button>
                        <button class="btn-secondary"> <a href="{% url 'snippets:index' %}" style="color: white;" >Cancelar</a></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

snippets/templates/snippets/snippet_edit.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row justify-content-md-center">
  <div class="col-md-6">
    <br>
    <form action="." method="post">
      {% csrf_token %}
      {{form|crispy}}
      <button type="submit" class="btn btn-primary">Modificar</button>
    </form>
  </div>
</div>
{% endblock %}

snippets/templates/snippets/user_snippets.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="row justify-content-md-center">
    <div class="col-md-8">
        <h1>Snippets: {{user.username}}</h1>
        <br>
        <!-- Snippets Publicos-->
        {% if public_snippets %}
        {% for ps in public_snippets %}
        <!-- SNIPPET -->
        <div class="card">
            <h5 class="card-header">{{ps.name}} <a href="{% url 'snippets:user_snippets' ps.user.id %}"  class="float-right"><small>{{ps.user.username}}</small></a></h5>
            <div class="card-body">
                <a href="{% url 'snippets:language' ps.language.id %}"><h5 class="card-title">{{ps.language.name}}</h5></a> 
                <h6 class="card-subtitle mb-2 text-muted">Creado: {{ps.created}}</h6>
                <p class="card-text">{{ps.description}}</p>
                <hr>
                <a href="{% url 'snippets:snippet' ps.id %}" class="btn btn-primary">Ver</a>
                {% if request.user == user %}
                <a href="{% url 'snippets:snippet_edit' ps.id %}" class="btn btn-info">Editar</a>
                <a href="{% url 'snippets:snippet_delete' ps.id %}" class="btn btn-danger">Eliminar</a>
                {% endif %}
            </div>
        </div>
        <br>
        <!-- FIN SNIPPET -->
        {% endfor %}
        {% endif %}
        <!-- Fin Snippets Publicos-->

        <!-- Snippets Privados -->
        {% if private_snippets %}
        {% for prs in private_snippets %}
        <!-- SNIPPET -->
        <div class="card">
            <h5 class="card-header">{{prs.name}} <span class="badge badge-warning">Privado</span> <a href="{% url 'snippets:user_snippets' prs.user.id %}"  class="float-right"><small>{{prs.user.username}}</small></a></h5>
            <div class="card-body">
                <a href="{% url 'snippets:language' prs.language.id %}"><h5 class="card-title">{{prs.language.name}}</h5></a> 
                <h6 class="card-subtitle mb-2 text-muted">Creado: {{prs.created}}</h6>
                <p class="card-text">{{prs.description}}</p>
                <hr>
                <a href="{% url 'snippets:snippet' prs.id %}" class="btn btn-primary">Ver</a>
                <a href="{% url 'snippets:snippet_edit' prs.id %}" class="btn btn-info">Editar</a>
                <a href="{% url 'snippets:snippet_delete' prs.id %}" class="btn btn-danger">Eliminar</a>
            </div>
        </div>
        <br>
        <!-- FIN SNIPPET -->

        {% endfor %}
        {% endif %}
        <!-- Fin Snippets Privados -->

  </div>
</div>
{% endblock %}